// Sketch registry: the home page and course pages are generated from this list.
// Entry: { id, title, description, load, group?, course?, unit?, planned?, related?, prereqs? }
//   group    'misc' (default) | 'course'
//   course   course id (COURSES[].id) for group 'course'
//   unit     1-based position inside the course
//   planned  true -> no `load`; shown as a disabled "coming soon" card
//   related  [{ id, label, why, params? }]  static cross links; params are appended as ?k=v
//   prereqs  [ids] units/sketches worth knowing first
// The id 'course' is reserved by the router (#/course/<courseId>).
export const SKETCHES = [
  {
    id: 'approx',
    group: 'misc',
    title: 'Function Approximation Lab',
    description: 'Taylor, Pade, Fourier and wavelet approximations of real and complex functions.',
    load: () => import('./approx/index.js'),
  },
  {
    id: 'hello',
    group: 'misc',
    title: 'Hello (demo)',
    description: 'Tiny demo sketch exercising settings, the drawer UI, p5 instance mode and unmounting.',
    load: () => import('./hello/index.js'),
  },
  {
    id: 'monge',
    group: 'misc',
    title: "Monge's Theorem",
    description: 'Drag three circles: the intersection points of their external common tangents always lie on one line.',
    load: () => import('./monge/index.js'),
  },
  {
    id: 'fourier2d',
    group: 'misc',
    title: 'Fourier Painter',
    description: 'Draw a curve and watch epicycles fit it, or paint an image and keep only some 2D frequencies.',
    load: () => import('./fourier2d/index.js'),
  },
  {
    id: 'equal-area',
    group: 'misc',
    title: 'Equal-Area Transformations',
    description: 'Slide a vertex parallel to the opposite side: the area never changes. Triangles, polygon reduction and squaring the triangle.',
    load: () => import('./equal-area/index.js'),
  },
  {
    id: 'conformal',
    group: 'misc',
    title: 'Conformal Maps',
    description: 'Grids, angles and local magnification under complex maps: z\u00b2, exp, sin, Joukowski, M\u00f6bius, polynomials.',
    load: () => import('./conformal/index.js'),
  },
  {
    id: 'chladni',
    group: 'misc',
    title: 'Chladni Plates',
    description: 'Vibrating square, rectangular and circular plates: eigenmodes, mode mixing, driven resonance sweeps, nodal lines and sand.',
    load: () => import('./chladni/index.js'),
  },
  {
    id: 'iso',
    group: 'misc',
    title: 'Marching Squares & Cubes',
    description: 'Contours and isosurfaces of scalar fields: inspect single cells, the 256 cube cases, cracks and slices.',
    load: () => import('./iso/index.js'),
  },
  {
    id: 'impulse',
    group: 'misc',
    title: 'Impulse Response Lab',
    description: 'Draw an input and an output like a terrain and recover the impulse response h with y = x * h, in time and frequency.',
    load: () => import('./impulse/index.js'),
  },
  {
    id: 'poncelet',
    group: 'misc',
    title: "Poncelet's Porism",
    description: 'Two conics, a chain of tangents: if the polygon closes for one start point it closes for all of them.',
    load: () => import('./poncelet/index.js'),
  },
  {
    id: 'geodesics',
    group: 'misc',
    title: 'Surface Curvature & Geodesics',
    description: 'Curvature of parametric surfaces, geodesics and shortest paths, parallel transport, holonomy and Gauss-Bonnet.',
    load: () => import('./geodesics/index.js'),
  },
  {
    id: 'elliptic',
    group: 'misc',
    title: 'Elliptic Curve Group',
    description: 'Chord-and-tangent addition on y\u00b2 = x\u00b3 + ax + b over the reals, over finite fields F_p, and via the complex torus C/(Z + \u03c4Z).',
    load: () => import('./elliptic/index.js'),
  },
  {
    id: 'kleinian',
    group: 'misc',
    title: 'Iterated Function Systems & Moebius Groups',
    description: 'Affine IFS fractals by the chaos game, and Schottky / Kleinian group limit sets on the plane and the Riemann sphere.',
    load: () => import('./kleinian/index.js'),
  },
  {
    id: 'em-electrostatics',
    group: 'course',
    course: 'em',
    unit: 1,
    title: "Electrostatics: Fields, Potential & Gauss's Law",
    description: "Point charges and distributions: field lines, equipotentials, flux through closed surfaces and a numerical check of Gauss's law.",
    load: () => import('./em-electrostatics/index.js'),
    prereqs: [],
    related: [
      { id: 'em-poisson', label: 'Laplace & Poisson solver', why: 'Solve for the potential with conductors and boundary conditions' },
      { id: 'ma-vector', label: 'Vector calculus', why: 'Divergence and the flux theorem behind Gauss' },
    ],
  },
  {
    id: 'em-poisson',
    group: 'course',
    course: 'em',
    unit: 2,
    title: 'Laplace & Poisson Solver: Conductors & Capacitance',
    description: 'Relaxation solvers for the potential between conductors, with charge density, boundary conditions and capacitance read-outs.',
    load: () => import('./em-poisson/index.js'),
    prereqs: ['em-electrostatics'],
    related: [
      { id: 'em-electrostatics', label: 'Electrostatics', why: 'Point-charge fields that the solver should reproduce' },
      { id: 'ma-pde', label: 'PDEs by Fourier series', why: 'Series solutions of Laplace on a rectangle' },
    ],
  },
  {
    id: 'em-magnetostatics',
    group: 'course',
    course: 'em',
    unit: 3,
    title: 'Magnetostatics: Biot-Savart, Ampere & the Lorentz Force',
    description: "Fields of wires, loops and solenoids from Biot-Savart, Ampere's circulation law and charged-particle motion under the Lorentz force.",
    planned: true,
    prereqs: ['em-electrostatics'],
    related: [
      { id: 'ma-vector', label: 'Vector calculus', why: "Curl and Stokes behind Ampere's law" },
      { id: 'em-electrostatics', label: 'Electrostatics', why: 'Compare the electric and magnetic field laws' },
    ],
  },
  {
    id: 'em-fdtd',
    group: 'course',
    course: 'em',
    unit: 4,
    title: 'Maxwell in Action: 2D FDTD Waves',
    description: 'Finite-difference time-domain simulation of the 2D Maxwell equations: sources, reflection, refraction and slits.',
    planned: true,
    prereqs: ['em-magnetostatics'],
    related: [
      { id: 'em-tline', label: 'Transmission lines', why: '1D wave propagation and reflection coefficients' },
      { id: 'em-antenna', label: 'Antenna arrays', why: 'Far-field radiation of several sources' },
    ],
  },
  {
    id: 'em-tline',
    group: 'course',
    course: 'em',
    unit: 5,
    title: 'Transmission Lines & the Smith Chart',
    description: 'Standing waves, reflection coefficient and impedance matching on a line, visualised on the Smith chart.',
    load: () => import('./em-tline/index.js'),
    prereqs: ['em-fdtd'],
    related: [
      { id: 'conformal', label: 'Conformal maps', why: 'The Smith chart is a Moebius transform of the impedance plane' },
      { id: 'em-fdtd', label: 'FDTD waves', why: 'Time-domain view of the same reflections' },
    ],
  },
  {
    id: 'em-antenna',
    group: 'course',
    course: 'em',
    unit: 6,
    title: 'Antenna Arrays & Radiation Patterns',
    description: 'Array factor, beam steering, grating lobes and polar radiation patterns of linear and planar antenna arrays.',
    load: () => import('./em-antenna/index.js'),
    prereqs: ['em-fdtd'],
    related: [
      { id: 'fourier2d', label: 'Fourier painter', why: 'The array factor is the Fourier transform of the element weights' },
      { id: 'impulse', label: 'Impulse response lab', why: 'Convolution and frequency-response viewpoint' },
    ],
  },
  {
    id: 'ma-linalg',
    group: 'course',
    course: 'engmath',
    unit: 1,
    title: 'Linear Algebra: Transformations, Eigen & SVD',
    description: 'See matrices as linear maps of the plane: eigenvectors, determinant, singular value decomposition and least squares.',
    planned: true,
    prereqs: [],
    related: [
      { id: 'equal-area', label: 'Equal-area transformations', why: 'Determinant as area scaling' },
      { id: 'ct-statespace', label: 'State space', why: 'Eigenvalues of A as system poles' },
    ],
  },
  {
    id: 'ma-ode',
    group: 'course',
    course: 'engmath',
    unit: 2,
    title: 'ODEs: Direction Fields, Phase Portraits & Solvers',
    description: 'Direction fields, phase portraits and numerical solvers (Euler, RK4) for first- and second-order ODEs, with stability read-outs.',
    planned: true,
    prereqs: ['ma-linalg'],
    related: [
      { id: 'ct-response', label: 'Time response', why: 'Second-order ODE responses and pole locations' },
      { id: 'ma-linalg', label: 'Linear algebra', why: 'Eigenvalues classify linear phase portraits' },
    ],
  },
  {
    id: 'ma-laplace',
    group: 'course',
    course: 'engmath',
    unit: 3,
    title: 'Laplace Transform & the s-Plane',
    description: 'Poles and zeros in the s-plane, inverse transforms by partial fractions and the link between pole locations and time signals.',
    planned: true,
    prereqs: ['ma-ode'],
    related: [
      { id: 'ct-response', label: 'Time response', why: 'Pole positions shape the step response' },
      { id: 'impulse', label: 'Impulse response lab', why: 'Convolution and transfer functions' },
    ],
  },
  {
    id: 'ma-vector',
    group: 'course',
    course: 'engmath',
    unit: 4,
    title: 'Vector Calculus: Divergence, Curl, Green & Stokes',
    description: "Vector fields with live divergence and curl, line and flux integrals, and numeric checks of Green's and Stokes' theorems.",
    load: () => import('./ma-vector/index.js'),
    prereqs: ['ma-linalg'],
    related: [
      { id: 'em-electrostatics', label: 'Electrostatics', why: 'Divergence and flux in Gauss law' },
      { id: 'em-magnetostatics', label: 'Magnetostatics', why: 'Curl and circulation in Ampere law' },
    ],
  },
  {
    id: 'ma-pde',
    group: 'course',
    course: 'engmath',
    unit: 5,
    title: 'PDEs by Fourier Series: Heat, Wave & Laplace',
    description: 'Separation of variables: Fourier series solutions of the heat, wave and Laplace equations with animated partial sums.',
    load: () => import('./ma-pde/index.js'),
    prereqs: ['ma-ode', 'ma-vector'],
    related: [
      { id: 'chladni', label: 'Chladni plates', why: 'Eigenmodes of a vibrating plate' },
      { id: 'approx', label: 'Function approximation', why: 'Fourier series convergence and the Gibbs phenomenon' },
    ],
  },
  {
    id: 'ma-residue',
    group: 'course',
    course: 'engmath',
    unit: 6,
    title: 'Complex Integration & Residues',
    description: "Contour integrals, Cauchy's theorem and the residue theorem, with poles, branch cuts and real-integral evaluation.",
    load: () => import('./ma-residue/index.js'),
    prereqs: ['ma-laplace'],
    related: [
      { id: 'conformal', label: 'Conformal maps', why: 'Complex maps as geometry' },
      { id: 'ct-freq', label: 'Bode & Nyquist', why: 'The argument principle behind the Nyquist criterion' },
    ],
  },
  {
    id: 'ct-response',
    group: 'course',
    course: 'ctrl',
    unit: 1,
    title: 'Time Response & Pole Locations',
    description: 'Step and impulse responses of first- and second-order systems: rise time, overshoot, settling time and damping from pole locations.',
    planned: true,
    prereqs: ['ma-laplace'],
    related: [
      { id: 'ma-ode', label: 'ODEs', why: 'The differential equation behind the response' },
      { id: 'impulse', label: 'Impulse response lab', why: 'Convolution with the impulse response' },
    ],
  },
  {
    id: 'ct-pid',
    group: 'course',
    course: 'ctrl',
    unit: 2,
    title: 'PID Control Lab',
    description: 'Tune P, I and D gains on a simulated plant: disturbances, noise, saturation and anti-windup, with performance metrics.',
    planned: true,
    prereqs: ['ct-response'],
    related: [
      { id: 'ct-response', label: 'Time response', why: 'Read the closed-loop behaviour directly' },
      { id: 'ct-rootlocus', label: 'Root locus', why: 'How the gains move the closed-loop poles' },
    ],
  },
  {
    id: 'ct-rootlocus',
    group: 'course',
    course: 'ctrl',
    unit: 3,
    title: 'Root Locus',
    description: 'Draw the root locus as the loop gain varies: asymptotes, break-away points, imaginary-axis crossings and gain read-outs.',
    planned: true,
    prereqs: ['ct-response'],
    related: [
      { id: 'ct-response', label: 'Time response', why: 'Step response at the chosen gain' },
      { id: 'ct-freq', label: 'Bode & Nyquist', why: 'The same loop in the frequency domain' },
    ],
  },
  {
    id: 'ct-freq',
    group: 'course',
    course: 'ctrl',
    unit: 4,
    title: 'Bode, Nyquist & Stability Margins',
    description: 'Bode and Nyquist plots of a loop transfer function, gain and phase margins, and the link to time-domain behaviour.',
    planned: true,
    prereqs: ['ct-rootlocus'],
    related: [
      { id: 'ma-residue', label: 'Complex integration', why: 'Argument principle and the Nyquist contour' },
      { id: 'ct-rootlocus', label: 'Root locus', why: 'Poles versus gain for the same plant' },
    ],
  },
  {
    id: 'ct-statespace',
    group: 'course',
    course: 'ctrl',
    unit: 5,
    title: 'State Space: Pole Placement, LQR & Observers (Cart-Pole)',
    description: 'State-space design on a cart-pole: pole placement, LQR weights, observers and the effect of noise.',
    planned: true,
    prereqs: ['ct-freq', 'ma-linalg'],
    related: [
      { id: 'ma-linalg', label: 'Linear algebra', why: 'Eigenvalues and controllability matrices' },
      { id: 'ct-pid', label: 'PID lab', why: 'Compare with classical control' },
    ],
  },
  {
    id: 'ct-digital',
    group: 'course',
    course: 'ctrl',
    unit: 6,
    title: 'Digital Control: Sampling & the z-Plane',
    description: 'Sampling, zero-order hold, aliasing and discretisation: map s-plane poles to the z-plane and watch stability change with the sample time.',
    planned: true,
    prereqs: ['ct-freq'],
    related: [
      { id: 'approx', label: 'Function approximation', why: 'Pade and discretisation approximations' },
      { id: 'ct-statespace', label: 'State space', why: 'Discrete-time state feedback' },
    ],
  },
];

export const COURSES = [
  {
    id: 'em',
    title: 'Electromagnetics',
    description: 'From static fields and potential theory to waves, transmission lines and antennas.',
    accent: '#4fc3f7',
    units: ['em-electrostatics', 'em-poisson', 'em-magnetostatics', 'em-fdtd', 'em-tline', 'em-antenna'],
  },
  {
    id: 'engmath',
    title: 'Engineering Mathematics',
    description: 'Linear algebra, differential equations, transforms, vector calculus, PDEs and complex integration.',
    accent: '#ffb74d',
    units: ['ma-linalg', 'ma-ode', 'ma-laplace', 'ma-vector', 'ma-pde', 'ma-residue'],
  },
  {
    id: 'ctrl',
    title: 'Control Systems',
    description: 'Time response, PID, root locus, frequency methods, state space and digital control.',
    accent: '#81c784',
    units: ['ct-response', 'ct-pid', 'ct-rootlocus', 'ct-freq', 'ct-statespace', 'ct-digital'],
  },
];
